language: python
python: "3.6"   
services:
  - xvfb
addons:
  chrome: stable
before_install: 
  - pip install -U pytest
  - wget -N https://chromedriver.storage.googleapis.com/87.0.4280.20/chromedriver_linux64.zip -P ~/
  - unzip ~/chromedriver_linux64.zip -d ~/
  - rm ~/chromedriver_linux64.zip
  - sudo mv -f ~/chromedriver /usr/local/share/
  - sudo chmod +x /usr/local/share/chromedriver
install: 
  - pip install -r requirements.txt
script: 
  - python -m py_compile Email-Client/run.py
  - python Email-Client/test-launch-client.py

